import{a as m,S as g,i as f}from"./assets/vendor-b0d10f48.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const h="https://pixabay.com",L="/api/",p=async(e,s=1,n=15)=>{try{return(await m.get(`${h}${L}`,{params:{key:"44189121-1bd84ab9c2376b17257837ab7",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:n}})).data}catch(r){throw console.error("Error fetching images :",r),r}};p();const b=new g(".gallery a");function v(e){const s=document.querySelector(".gallery"),n=e.map(r=>`<a href="${r.largeImageURL}"  class="gallery-item" >
<img src="${r.webformatURL}" alt="${r.tags}" />
<div class="info">¨
  <p class="info-title">Likes: <span class="info-value">${r.likes}</span> </p>
  <p class="info-title">Views: <span class="info-value">${r.views}</span></p>
  <p class="info-title">Comments: <span class="info-value">${r.comments}</span></p>
  <p class="info-title">Downloads: <span class="info-value">${r.downloads}</span></p>
</div>
</a>`).join("");s.insertAdjacentHTML("beforeend",n),b.refresh()}function w(){document.querySelector(".loader").style.display="block"}function u(){document.querySelector(".loader").style.display="none"}function l(e){f.error({title:"Error",message:e,posision:"topRight"})}const q=()=>{document.querySelector(".gallery").innerHTML=""},d=e=>{const s=document.querySelector(".load-more");s.style.display=e?"block":"none"},S=()=>{const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})};let c="",a="";const E=document.querySelector(".form"),$=document.querySelector(".load-more"),y=async()=>{w();try{const e=await p(c,a);if(u(),e.hits.length===0&&a===1){l("Sorry, there are no images matching your search query. Please try again!");return}v(e.hits),a+=1,a*15>=e.totalHits?(d(!1),f.info({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):d(!0),S()}catch(e){u(),l("Failed to fetch images. Please try again later!"),console.log(e)}};E.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements.query.value.trim(),!c){l("Please enter a search query!");return}a=1,q(),await y()});$.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
