import{a as y,S as m,i as h}from"./assets/vendor-b0d10f48.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const g="https://pixabay.com",L="/api/",f=async(e,s=1,a=15)=>{try{return(await y.get(`${g}${L}`,{params:{key:"44189121-1bd84ab9c2376b17257837ab7",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:a}})).data}catch(r){throw console.error("Error fetching images :",r),r}};f();function b(e){const s=document.querySelector(".gallery"),a=e.map(r=>`<a href="${r.largeImageURL}"  class="gallery-item" >
<img src="${r.webformatURL}" alt="${r.tags}" />
<div class="info">¨
  <p class="info-title">Likes: <span class="info-value">${r.likes}</span> </p>
  <p class="info-title">Views: <span class="info-value">${r.views}</span></p>
  <p class="info-title">Comments: <span class="info-value">${r.comments}</span></p>
  <p class="info-title">Downloads: <span class="info-value">${r.downloads}</span></p>
</div>
</a>`).join("");s.insertAdjacentHTML("beforeend",a),new m(".gallery a").refresh()}function v(){document.querySelector(".loader").style.display="block"}function u(){document.querySelector(".loader").style.display="none"}function l(e){h.error({title:"Error",message:e,posision:"topRight"})}const w=()=>{document.querySelector(".gallery").innerHTML=""},d=e=>{const s=document.querySelector(".load-more");s.style.display=e?"block":"none"},q=()=>{const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})},S=document.querySelector(".form"),E=document.querySelector(".load-more");let c="",n="";S.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements.query.value.trim(),!c){l("Please enter a search query!");return}n=1,w(),await p()});const p=async()=>{v();try{const e=await f(c,n);if(u(),e.hits.lenght===0&&pade===1){l("Sorry, there are no images matching your search query. Please try again!");return}b(e.hits),n+=1,E.addEventListener("click",p),n*15>=e.totalHits?(d(!1),iziToast.info({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"})):d(!0),q()}catch(e){u(),l("Failed to fetch images. Please try again later!"),console.log(e)}};
//# sourceMappingURL=commonHelpers.js.map
